### ISSUE TITLE
I'm not able to mock s3 with typescript

### ISSUE THREAD

**Issue by victorgsp** [dwyl/aws-sdk-mock#264]
Hi guys, i'm not able to mock s3 with typescript
**my code**
`
  import * as AWS from "aws-sdk";
  class S3Provider {
    public async getS3ObjectList() {
      const s3 = new AWS.S3();
  
      const params: AWS.S3.ListObjectsV2Request = {
        Bucket: Environment.RAW_DATA_BUCKET_NAME,
      };
      const list: AWS.S3.ListObjectsV2Output = await s3
        .listObjectsV2(params)
        .promise();
      return list;
    }
`

**my test**
`
...
import * as AWSMock from "aws-sdk-mock";
import * as AWS from "aws-sdk";

describe("Mytest", () => {
  it("should return a correct value", async () => {
    AWSMock.setSDKInstance(AWS);

    AWSMock.mock("S3", "listObjectsV2", output);

    const provider = new getS3ObjectList();
    const result = await provider.getS3ObjectList();
...
`
Error:
`
UriParameterError: Expected uri parameter to have length >= 1, but found "" for params.Bucket

      at ParamValidator.fail (node_modules/aws-sdk/lib/param_validator.js:50:37)
      at ParamValidator.validateUri (node_modules/aws-sdk/lib/param_validator.js:167:14)
      at ParamValidator.validateString (node_modules/aws-sdk/lib/param_validator.js:160:12)
      at ParamValidator.validateScalar (node_modules/aws-sdk/lib/param_validator.js:132:21)
      at ParamValidator.validateMember (node_modules/aws-sdk/lib/param_validator.js:96:21)
      at ParamValidator.validateStructure (node_modules/aws-sdk/lib/param_validator.js:77:14)
      at ParamValidator.validateMember (node_modules/aws-sdk/lib/param_validator.js:90:21)
      at ParamValidator.validate (node_modules/aws-sdk/lib/param_validator.js:34:10)
      at Request.VALIDATE_PARAMETERS (node_modules/aws-sdk/lib/event_listeners.js:132:42)
      at Request.callListeners (node_modules/aws-sdk/lib/sequential_executor.js:106:20)
`

**Comment by nelsonic** [comment]
@victorgsp were you able to resolve the issue? 🤞
