### ISSUE TITLE
How to mock an event (S3.ManagedUpload)??

### ISSUE THREAD

**Issue by e8315402** [dwyl/aws-sdk-mock#99]
I want to ask is there any way to mock event of some services ??

This is a part of my code:
``` js
function (fileParam, updateProgress) {
  if (s3 === undefined) s3 = new AWS.S3()
  let upload = s3.upload(fileParam)
  if (typeof (updateProgress) === 'function')
        upload.on('httpUploadProgress', updateProgress)
  return upload.promise()
}
```
After mock `S3.upload()`, it is fine to use `promise()` and `createReadStream()`.
But there is a error because of `upload.on('httpUploadProgress', updateProgress)`
``` js
TypeError: upload.on is not a function
      at uploadOneFile (app/src/main/s3.js:77:54)
      at Object.uploadClipToS3 (app/src/main/s3.js:37:24)
      at Context.<anonymous> (test/unit/specs/S3.spec.js:156:8)
```

So... is there any way to mock event or how to handle this ??
Thank a lot !!

**Comment by danieljin** [comment]
Bump!

**Comment by phg98** [comment]
Hi, I have same problem.
Did you find the solution for this problem?
Thanks!
